image: python:3.10

variables:
  HTTP_PROXY: "http://webproxy:8080/"
  HTTPS_PROXY: "http://webproxy:8080/"

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install ".[lint, docs]"

stages:
  - static_tests
  - documentation
    
lint:
  stage: static_tests
  allow_failure: true
  script:
    - poe lint

pages:
  stage: documentation
  script:
  - sphinx-build -b html ./docs ./docs/public
  artifacts:
    paths:
    - ./docs/public
  only:
  - main
  - development
