image: python:3.10

variables:
  HTTP_PROXY: "http://webproxy:8080/"
  HTTPS_PROXY: "http://webproxy:8080/"

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install ".[lint]"

stages:
  - Static Analysis
    
lint:
  stage: Static Analysis
  script:
    - poe lint