image: python:3.10

variables:
  HTTP_PROXY: "http://webproxy:8080/"
  HTTPS_PROXY: "http://webproxy:8080/"

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install ".[lint]"

stages:
  - static tests
  - documentation
    
lint:
  stage: Static Analysis
  script:
    - poe lint

pages:
  stage: documentation
  script:
  - pip install -U sphinx
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  only:
  - main
  - development
