# Configuration file for OSI²One pypulseq-console

# Spectrum instrumentation device configuration
# M2p.6546-x4 -> /dev/spcm1 (AWG)
TxCard: !TxCard
  path: '/dev/spcm1'
  max_amplitude: [100, 1000, 1000, 1000] # Max. amplitude per channel
  filter_type: [0, 2, 2, 2] # Filter per channel
  sample_rate: 20  # in MHz
  notify_rate: 16

# M2p.5933-x4 -> /dev/spcm0 (Digitizer)
RxCard: !RxCard
  path: '/dev/spcm0'
  max_amplitude: [10000, 10000, 1000, 1000] # Max. amplitude per channel
  channel_enable: [1, 1, 1, 1] # Enable per channel
  sample_rate: 10         # in MHz
  memory_size: 4096000    # memory size in cycles, Please note that step size is 8. 
  loops: 0          # number of loops, 0 for infinite loop for FIFO gated mode. 
  timeStampMode: True
  # post_trigger: !!python/object/apply:eval [memory_size - 8000] ##Todo #Note that step size is 8

# Sequence provider configuration
SequenceProvider: !SequenceProvider
  spcm_dwell_time: 0.00000005 # 5e-8 => 20 MHz
  rf_double_precision: True
  grad_to_volt: 0.001
  rf_to_volt: 0.005

  # TODO: Review the following values
  system: !Opts
    max_grad: 250000.0
    max_slew: 250000.0
    rise_time: 0
    rf_dead_time: 0.00005  # 50us
    rf_ringdown_time: 0
    adc_dead_time: 0
    B0: 0.0477
