# Spectrum instrumentation device configuration

devices:

  # M2p.6546-x4 -> /dev/spcm0 (AWG)
  - !TxCard
    path: '/dev/spcm0'
    amplitude: 1
    # notify_size_samples: 2048  # number of samples
    buffer_size_samples: 65536
    sample_rate: 2  # MHz

  # M2p.5933-x4 -> /dev/spcm1 (Digitizer)
  - !RxCard
    path: '/dev/spcm1'


system: 
  - !System
    # ADC
    adc_dead_time: 0
    # Gradents
    grad_raster_time: 10e-6
    rise_time: 0
    max_grad: 10 # in Hz/m
    max_slew: 5 # in Hz/m/s
    # RF
    rf_dead_time: 50
    rf_raster_time: 1e-6
    rf_ringdown_time: 0
      
