# Configuration file for OSI²One pypulseq-console

# Spectrum instrumentation device configuration
# M2p.6546-x4 -> /dev/spcm1 (AWG)
TxCard: !TxCard
  path: '/dev/spcm1'
  max_amplitude: [1000, 1000, 1000, 1000] # Max. amplitude per channel
  filter_type: [0, 2, 2, 2] # Filter per channel
  sample_rate: 20  # in MHz
  notify_rate: 16

# M2p.5933-x4 -> /dev/spcm0 (Digitizer)
RxCard: !RxCard
    path: '/dev/spcm0'

# Sequence provider configuration
SequenceProvider: !SequenceProvider
  spcm_sample_rate: 0.00000005 # 5e-8 => 20 MHz
  rf_double_precision: True
  grad_to_volt: 0.005
  rf_to_volt: 0.1
  # TODO: Set system limits
  system: !Opts
    max_grad: 250000.0
    max_slew: 250000.0
    rise_time: 0
    rf_dead_time: 0
    rf_ringdown_time: 0
    adc_dead_time: 0
    B0: 0.05