# Device settings for spectrum cards

spcm_cards:

  # M2p.6546-x4 -> /dev/spcm0 (AWG)
  - !SpectrumDevice
    path: '/dev/spcm0'

  # M2p.5933-x4 -> /dev/spcm1 (Digitizer)
  - !SpectrumDevice
    path: '/dev/spcm1'
