# ========================================
# Configuration file for the Nexus-console
# ========================================

# NOTE: This is just an example, parameters need to be adjusted for individual system

# >> TX DEVICE: M2p.6546-x4 -> /dev/spcm1 (AWG)
# Total number of (analog) transmit channels: 4
TxConfiguration:
  # Could be extended to a list
  device_path: "/dev/spcm1"
  # Number of channels
  max_available_channels: 4
  # Device sampling rate in MHz
  sampling_rate: 20
  # Max. output amplitude per channel in mV
  channel_max_amplitude: [200, 6000, 6000, 6000]
  # Filter configuration of each transmit channel
  channel_filter_type: [0, 2, 2, 2]
  # Configure which channels are terminated into 50 ohm impedance (true == 50 ohm), list length must at least match the number of enabled channels
  channel_terminated_50ohm: [True, False, False, False]
  # Calculate grad_to_volt per gradient channel:
  # Gradient efficiency in T/m/A
  gradient_efficiency: [0.37e-3, 0.451e-3, 0.4e-3]
  # Gradient power amplifier in V/A
  gpa_gain: [7.10, 7.10, 7.10]
  # Scales RF in Hz (pulseq) to mV
  rf_to_mvolt: 5.e-3

# >> RX DEVICE: M2p.5933-x4 -> /dev/spcm0 (Digitizer)
# Total number of receive channels: 8
RxConfiguration:
  # Could be extended to a list
  device_path: "/dev/spcm0"
  # Number of channels
  max_available_channels: 4
  # Device sampling rate in MHz
  sampling_rate: 20
  # Enable the receive channels
  channel_enable: [1, 0, 0, 0, 0, 0, 0, 0]
  # Set the max. amplitude per channel in mV, list length must at least match the number of enabled channels
  channel_max_amplitude: [200, 200, 200, 200, 1000, 1000, 1000, 1000]
  # Configure which channels are terminated into 50 ohm impedance (true == 50 ohm), list length must at least match the number of enabled channels
  channel_terminated_50ohm: [True, True, True, True, False, False, False, False]

SystemLimits:
  # Maximum gradient amplitude in Hz/m (PyPulseq system stores this unit)
  max_grad: 10644000000.0 # equals 250 T/m
  # Maximum slew rate in Hz/m/s (PyPulseq system stores this unit)
  max_slew: 4257600000.0 # equals 100 T/m/s
  # Dead time at the beginning of RF event in s, covered by rf_delay
  rf_dead_time: 20.e-6
  # Time delay at the end of an RF event in s
  rf_ringdown_time: 20.e-6
  # Time delay at the beginning of an ADC event in s
  adc_dead_time: 0.
  block_duration_raster: 5.e-8
  rf_raster_time: 5.e-8
  grad_raster_time: 5.e-8
  adc_raster_time: 5.e-8
